print("==========================")
print("    BEST FRIEND MAKER")
print("==========================")
print()
print("Hi. I'm the computer")
name = input("What's your name? ")
color = input(f"Hi, {name}! what's your favorite color? ")
print(f"no way! my favorite color is also {color}!")
movie = input("what's your favorite movie? ")
print(f"what!?! My favorite movie is also {movie}! ")
game = input("what is your favorite game? ")
print(f"Get out of here! my favorite game is {game} too!")
pizza = input("what is your least favorite pizza topping? ")
print(f"I dislike {pizza} on my pizza! just like you!")
Class = input(f"what is your favorite class? ")
print(f"wow! my favorite class is {Class}, as well!")
print("we like the same things! we should become best friends!")
